/** Uyghur education alphabet used by the game client and admin tools. */
export const EDUCATION_LETTERS = [
  'خ',
  'چ',
  'ج',
  'ت',
  'پ',
  'ب',
  'ئە',
  'ئا',
  'ف',
  'غ',
  'ش',
  'س',
  'ژ',
  'ز',
  'ر',
  'د',
  'ھ',
  'ن',
  'م',
  'ل',
  'ڭ',
  'گ',
  'ك',
  'ق',
  'ي',
  'ئى',
  'ئې',
  'ۋ',
  'ئۈ',
  'ئۆ',
  'ئۇ',
  'ئو',
] as const;

export type EducationLetter = (typeof EDUCATION_LETTERS)[number];

/** Physical key sequence required to type each education letter. */
export const TYPING_SEQUENCE = new Map<EducationLetter, readonly string[]>([
  ['خ', ['shift', 'ى']],
  ['چ', ['چ']],
  ['ج', ['shift', 'ق']],
  ['ت', ['ت']],
  ['پ', ['پ']],
  ['ب', ['ب']],
  ['ئە', ['ئ', 'ە']],
  ['ئا', ['ئ', 'ا']],
  ['ف', ['shift', 'ا']],
  ['غ', ['غ']],
  ['ش', ['ش']],
  ['س', ['س']],
  ['ژ', ['shift', 'د']],
  ['ز', ['ز']],
  ['ر', ['ر']],
  ['د', ['د']],
  ['ھ', ['ھ']],
  ['ن', ['ن']],
  ['م', ['م']],
  ['ل', ['ل']],
  ['ڭ', ['ڭ']],
  ['گ', ['shift', 'ە']],
  ['ك', ['ك']],
  ['ق', ['ق']],
  ['ي', ['ي']],
  ['ئى', ['ئ', 'ى']],
  ['ئې', ['ئ', 'ې']],
  ['ۋ', ['ۋ']],
  ['ئۈ', ['ئ', 'ۈ']],
  ['ئۆ', ['ئ', 'shift', 'ك']],
  ['ئۇ', ['ئ', 'ۇ']],
  ['ئو', ['ئ', 'و']],
]);

/** Uyghur keyboard letter pool for typing-level configuration. */
export const KEYBOARD_LETTERS = [
  'چ',
  'ۋ',
  'ې',
  'ر',
  'ت',
  'ي',
  'ۇ',
  'ڭ',
  'و',
  'پ',
  'ھ',
  'س',
  'د',
  'ا',
  'ە',
  'ى',
  'ق',
  'ك',
  'ل',
  'ز',
  'ش',
  'غ',
  'ۈ',
  'ب',
  'ن',
  'م',
  'ئ',
  'ژ',
  'ف',
  'گ',
  'خ',
  'ج',
  'ۆ',
  'لا',
] as const;

export type KeyboardLetter = (typeof KEYBOARD_LETTERS)[number];
